FROM dunglas/frankenphp:php8.3

WORKDIR /app

# Install PHP extensions yang dibutuhkan Laravel + MySQL
RUN install-php-extensions \
    pdo_mysql \
    mbstring \
    bcmath \
    exif \
    pcntl \
    intl \
    zip \
    opcache

# Copy Composer dari image Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Copy seluruh project Laravel
COPY . .

# Install dependency production
RUN composer install \
    --no-dev \
    --optimize-autoloader \
    --no-interaction \
    --prefer-dist

# Permission Laravel
RUN mkdir -p storage/framework/cache \
    storage/framework/sessions \
    storage/framework/views \
    storage/logs \
    bootstrap/cache

RUN chmod -R 775 storage bootstrap/cache

# Laravel harus dilayani dari folder public
ENV SERVER_NAME=:80

# Vercel memberikan PORT secara otomatis
CMD ["sh", "-c", "frankenphp php-server -r public/ --listen 0.0.0.0:${PORT:-80}"]
